const s1 = {
  events: [
    [
      {
        from: [6, 3],
        to: [3, 3],
        type: 'shoot',
      },
    ],
  ],
  goal: [2, 3],
  monsters: [
    [3, 4],
    [5, 6],
    [4, 4, 'z'],
  ],
  player: [1, 1, 5],
  shield: 'east',
  walls: {
    '3,2': 'sand',
    '3,4': 'stone',
    '8, 1': 'solid',
    '15, 10': 'empty',
    '10, 1': 'solid',
    'a\b': 'empty',
    '1, 4': 'solid',
    '\t\n': 'empty',
    '\v\b': 'empty',
    '3, 10': 'empty',
    '8, 3': 'empty',
    '13, 2': 'solid',
    '6, 11': 'empty',
    '2, 5': 'empty',
    '12, 5': 'empty',
    '1, 2': 'solid',
    '2, 9': 'empty',
    '\b\v': 'empty',
    '\f\v': 'empty',
    '13, 6': 'solid',
    '\n\v': 'empty',
    '9, 4': 'empty',
    '2, 11': 'empty',
    '14, 5': 'empty',
    '10, 3': 'empty',
    '14, 3': 'empty',
    '8, 5': 'empty',
    '4, 9': 'empty',
    '5, 4': 'empty',
    '2, 7': 'empty',
    '13, 4': 'solid',
    '11, 4': 'empty',
    '\f\t': 'empty',
    '5, 8': 'empty',
    '3, 8': 'empty',
    '2, 3': 'empty',
    '2, 1': 'solid',
    '\b\t': 'empty',
    '1, 10': 'solid',
    '11, 6': 'empty',
    '6, 1': 'solid',
    '4, 7': 'empty',
    '15, 2': 'empty',
    '3, 6': 'empty',
    '11, 2': 'empty',
  },
}

export default { s1 }
